### PR TITLE
Logic error when checking for symbolized keys

### PR DESCRIPTION
**Pull request by kwando**
Current code was always symbolizing keys

### CODE REVIEW

**Comment by odlp** [comment]
Hi @kwando I'm not sure this is a error - looking at the implementation of `#keys_are_symbols?`
https://github.com/odlp/simplify_rb/blob/master/lib/simplify_rb.rb#L103

This `#keys_are_symbols?` method expects an array of keys, and uses `all?` within itself. 

My intention was to always deal with keys as symbols, to reduce memory footprint. If some keys are symbols, it symbolizes them (this is the current behaviour). If all the keys are already symbols, it carries on.

Would you like a mode to keep the keys as strings? If so we could add an option for this.

**Comment by kwando** [comment]
Your code is wrong since, try stepping through a debugger and you will see ;)

The `keys_are_symbols?` method is called once with an argument looking like this `[[:x, :y], [:x, :y]]` and `[[:x, :y], [:x, :y]].all?{|k| k.is_a?(Symbol)}` is always false..

**Comment by odlp** [comment]
Ah I see! Thank you for the explanation 👍 

I was misinterpreting the original code as sending a flattened array (e.g. `[:x, :y, :x, :y]`) rather than a nested array like `[[:x, :y], [:x, :y]]`.

Thanks again. I will try and make a new release shortly.

**Comment by kwando** [comment]
No problemo, sorry if I came across as rude or something. Was not intentional =)

**Comment by odlp** [comment]
Not at all, I was just confused! I just pushed version `0.1.3` to Rubygems with your fix included.

Thanks.

**Pull request merged**
